stages:
  - build
  - test

services:
- docker:stable-dind

image:
  docker/compose:latest

build:
  stage: build
  image: docker:stable-dind
  script:
    - docker login -u $DH_Uname -p $DH_pswd
    - docker build -t yehor.brilov/ci-cd-homework-v1.0.$CI_PIPELINE_IID .
  allow_failure: true
  tags:
    - docker-shared
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^dev/

test:
  stage: test
  image: docker:stable-dind
  script:
      - docker-compose 
          -p "$CI_PROJECT_NAME"_"$CI_PIPELINE_ID"
        up
          --abort-on-container-exit
          --exit-code-from app
          --quiet-pull
      - docker-compose down
  tags:
    - docker-shared
