include:
  - project: 'yehor.brilov/pipe'
    file: '/.gitlab-ci.yml'


stages:
  - build
  - test
  

image:
  name: docker/compose:latest

services:
  - docker:dind

Test:
  extends: test
  needs: ["Build Prod"]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1.0..*$/'
      when: on_success

Build Prod:
  extends: build
  variables:
    ENV: "Prod"
    VER: "$CI_COMMIT_TAG"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1.0..*$/'
      when: manual

Build Stage:
  extends: build
  variables:
    ENV: "Stage"
    VER: "v1.0.$CI_PIPELINE_IID-stage"


